version: "2"
services:
  postgres:
    image: library/postgres:10
    ports:
      - "5432:5432"
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=POSTGRES
  notebook:
    build:
      context: .
      dockerfile: jupyter.Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./src:/home/jovyan
